[versions]

java = "VERSION_11"
agp = "8.10.1"

# Build constants
minSdk = "26"
compileSdk = "36"
targetSdk = "36"

# Detekt
detekt = "1.23.3"
detektTwitterComposeRules ="0.0.26"

# UI
material3 = "1.4.0"

#glide
glide = "4.16.0"

#network
retrofit = "2.11.0"
gson = "2.13.1"

#room
room = "2.8.3"

#kotlin
koinAndroid = "4.0.4"
kotlin = "2.2.0"
kotlinxCoroutinesAndroid = "1.10.2"

runtimeLivedata = "1.9.4"
navigationFragment = "2.9.5"

[libraries]

# Detekt
staticAnalysis-detektPlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
staticAnalysis-detektCli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt" }
staticAnalysis-detektApi = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
staticAnalysis-detektTest = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }
staticAnalysis-detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
staticAnalysis-detektLibraries = { module = "io.gitlab.arturbosch.detekt:detekt-rules-libraries", version.ref = "detekt" }
staticAnalysis-detektTwitterComposeRules = { module = "com.twitter.compose.rules:detekt", version.ref = "detektTwitterComposeRules" }

# AndroidX
androidX-core = "androidx.core:core-ktx:1.17.0"
androidX-appCompat = "androidx.appcompat:appcompat:1.7.1"
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }

# UI layer libraries
ui-material = "com.google.android.material:material:1.13.0"
ui-constraintLayout = "androidx.constraintlayout:constraintlayout:2.2.1"
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

# Unit tests
unitTests-junit = "junit:junit:4.13.2"

# UI tests
uiTests-junitExt = "androidx.test.ext:junit:1.3.0"
uiTests-espressoCore = "androidx.test.espresso:espresso-core:3.7.0"

# Networking
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

# Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-runtime-android = { group = "androidx.room", name = "room-runtime-android", version.ref = "room" }

# kotlin
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }

# navigation
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragment" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragment" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }

[bundles]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
